import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styled from 'styled-components'
import 'text-to-speech-offline'

export default function Home() {
  const TTS = require('text-to-speech-offline');
  const MainContainer = styled.div`
    font-size: 32px;
  `;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <button onClick={() => TTS("すずかわあやこ", 'ja-JP')}>すずかわあやこ</button>
      </MainContainer>
    </>
  )
}
